version: '3.2'

services:
  mariadb:
    image: mariadb
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234!
      MYSQL_USER: mytest
      MYSQL_PASSWORD: mytest
    networks:
      - mynet
    volumes:
      - ../mariadb/db:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mynet

# You MUST run command 'docker create network mynet'
networks:
  mynet:
    driver: bridge

